"""Initial

Revision ID: 39c38b78c51c
Revises: 
Create Date: 2023-03-31 12:48:35.894656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39c38b78c51c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn', 'name', name='inn_mame_uc')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sub_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'sub_name', name='name_sub_name_uc')
    )
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('range', postgresql.INT8RANGE(), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    postgresql.ExcludeConstraint((sa.column('range'), '&&'), using='gist'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone')
    op.drop_table('region')
    op.drop_table('operator')
    # ### end Alembic commands ###
